config/routes.rb
Rails.application.routes.draw do
  # Root
  root 'static_pages#home'

  # Backend
  namespace :backend do
    resources :users
    resources :trials
    resources :memberships
  end

  get '/swalwell/join', to: 'static_pages#swalwell_join', as: 'swalwell_join'
  get '/cramlington/join', to: 'static_pages#cramlington_join', as: 'cramlington_join'
  #get '/cramlington', to: 'static_pages#cramlington', as: 'cramlington'
  #get '/cramlington/gym-info', to: 'static_pages#cramlington_gym_info', as: 'cramlington_gym_info'
  #post '/cramlington/register-lead-interest', to: 'static_pages#cramlington_register_lead_interest', as: 'cramlington_register_lead_interest'
  #get '/cramlington/confirmation', to: 'static_pages#register_interest_confirmation', as: 'register_interest_confirmation'

	scope '/policies' do
  	get '/cookie_policy', to: 'static_pages#cookie_policy', as: 'cookie_policy'
  	get '/privacy_policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
	end

  get '/members', to: 'members#index'
  post '/members/import', to: 'members#import', as: 'import_members'

  get '/members/:consent_to_market_token', to: 'members#consent_to_market', as: :consent_to_market
  get '/members/consent_accepted/:consent_to_market_token', to: 'members#consent_accepted', as: :consent_accepted
  patch '/members/:consent_to_market_token', to: 'members#set_consent_to_market'

  # Front end
  #resources :trials,
  #  :memberships, only: [:new, :create, :index]
  #get '/memberships/thank-you', to: 'memberships#confirmation'
  #get '/trial-membership/thank-you', to: 'trials#confirmation'

  #get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Classes
  get '/classes',                     to: 'static_pages#classes'
  #get '/classes/ab-solution',         to: 'static_pages#ab_solution'
  #get '/classes/bootcamp',            to: 'static_pages#bootcamp'
  #get '/classes/boxing',              to: 'static_pages#boxing'
  #get '/classes/circuit-training',    to: 'static_pages#circuit_training'
  #get '/classes/cycle-fit',           to: 'static_pages#cycle_fit'
  #get '/classes/cycle-pump',          to: 'static_pages#cycle_pump'
  #get '/classes/hiit',                to: 'static_pages#hiit'
  #get '/classes/kettle-x-fit',        to: 'static_pages#kettle_x_fit'
  #get '/classes/lbt',                 to: 'static_pages#lbt'
  #get '/classes/mma',                 to: 'static_pages#mma'
  #get '/classes/pilates',             to: 'static_pages#pilates'
  #get '/classes/pilates-hiit',        to: 'static_pages#pilates_hiit'
  #get '/classes/pumped',              to: 'static_pages#pumped'
  #get '/classes/rig-assault',         to: 'static_pages#rig_assault'
  #get '/classes/strength-and-conditioning',             to: 'static_pages#strength_and_conditioning'
  #get '/classes/total-body',          to: 'static_pages#total_body'
  #get '/classes/trx',                 to: 'static_pages#trx'
  #get '/classes/ultimate-endurance',  to: 'static_pages#ultimate_endurance'

  get '/facilities',                  to: 'static_pages#facilities'
  #get '/timetables',                  to: 'static_pages#timetables'

  get '/vhf_code_of_conduct',         to: 'static_pages#vhf_code_of_conduct'

  # Contact
  get '/contact',                     to: 'messages#new', as: 'new_message'
  post '/contact',                    to: 'messages#create', as: 'create_message'

  # Letter opener path for development only
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/gdpr_compliance/_gdpr_compliance_banner.html.erb
<div class="reveal medium" id="gdpr_compliance_banner" data-reveal data-close-on-click="false" data-close-on-esc="false">
  <div class="small-12 columns">
    <div class="gdpr_compliance_banner_heading">
      <%= I18n.t('gdpr_compliance.dialog.heading') %>
    </div>
    <div class="gdpr_compliance_banner_text">
      <p>To make sure you get the best experience on our website we use cookies. Find out more by reading our <%= link_to 'privacy policy', privacy_policy_path %>, or <%= link_to 'find out more about cookies', cookie_policy_path %>.</p>
    </div>

    <form class="gdpr_compliance_form">
      <div>
        <div class="gdpr_compliance_section">
          <div>
            <input id="gdpr_compliance_necessary" type="checkbox" disabled="true" checked>
            <label for="gdpr_compliance_necessary">
              <%= I18n.t('gdpr_compliance.dialog.body.necessary.checkbox_label') %>
            </label>
          </div>
          <div id="gdpr_compliance_necessary_text">
            <p><%= I18n.t('gdpr_compliance.dialog.body.necessary.introduction') %></p>
          </div>
        </div>
        </div>

        <div class="gdpr_compliance_section">
          <div>
            <input id="gdpr_compliance_preferences" type="checkbox" checked>
            <label for="gdpr_compliance_preferences">
              <%= I18n.t('gdpr_compliance.dialog.body.preferences.checkbox_label') %>
            </label>
          </div>
          <div id="gdpr_compliance_preferences_text">
            <p><%= I18n.t('gdpr_compliance.dialog.body.preferences.introduction') %></p>
          </div>
        </div>

        <div class="gdpr_compliance_section">
          <div>
            <input id="gdpr_compliance_statistics" type="checkbox" checked>
            <label for="gdpr_compliance_statistics">
              <%= I18n.t('gdpr_compliance.dialog.body.statistics.checkbox_label') %>
            </label>
          </div>
          <div id="gdpr_compliance_statistics_text">
            <p><%= I18n.t('gdpr_compliance.dialog.body.statistics.introduction') %></p>
          </div>
        </div>

        <div class="gdpr_compliance_section">
          <div>
            <input id="gdpr_compliance_marketing" type="checkbox">
            <label for="gdpr_compliance_marketing">
              <%= I18n.t('gdpr_compliance.dialog.body.marketing.checkbox_label') %>
            </label>
          </div>
          <div id="gdpr_compliance_marketing_text">
            <p><%= I18n.t('gdpr_compliance.dialog.body.marketing.introduction') %></p>
          </div>
        </div>
        <div class="gdpr_compliance_button">
          <input id="gdpr_compliance_button" type="button" value="Submit" class="button">
        </div>
      </div>
    </form>
  </div>
</div>

app/views/gdpr_compliance/_sign_up_privacy_statement.html.erb
<h2>Privacy Statement</h2>

<p>This statement outlines how and why we process your data. Please ensure you read and
understand it before proceeding.</p>

<p>We value your privacy and want to ensure you fully understand why we need your data and
how we may process it so that your decision to trust us with it, is an informed one.</p>

<h4>Your Personal Data</h4>

<div class="section">
	<p><strong>What we need:</strong></p>

	<p>Vision Health and Fitness Club Limited will be joint data controllers of the personal data you
	provide to us along with our service partners: Membr - Fit Cloud Technology Limited (who
	provide our gym management software) and Harlands Services Limited (who provide us with
	direct debit collections services). They will only have access to your data for the purposes of
	providing their services to us and their access to it is strictly governed by contracts with us.
	We only collect personal data relevant to the membership you have selected. The data we
	collect may include: Name, address, phone number, email address, emergency contact,
	financial details including bank details, your preferences and interests. We may also collect
	‘special’ data explained in more detail below.</p>
</div>

<div class="section">
	<p><strong>Special Data:</strong></p>

	<p>We don't use gym cards, pin codes etc for accessing our gym, they are easy to forget or lose.
	Instead we have a fingerprint access control system that uses a scan of your fingerprint to
	control your access into the gym. Upon your first visit, a member of our team will capture a
	scan of one fingerprint that you will then use on future visits to access the gym. Our
	fingerprint access system is provided by Nomical Limited who act as a third party processor
	over this data on our behalf under a strict legal agreement. They will never access your data
	without prior consent from us and it will never be shared or processed by anyone other than
	for the purposes of controlling your access to the gym. We have installed the necessary,
	technical, physical and legal safeguards to ensure this.</p>
</div>

<div class="section">
	<p><strong>Why we need it:</strong></p>

	<p>We need your data to fulfil our contractual requirements to you when we provide you with a
	gym membership and to manage that membership, control your access to our gym and
	collect any payments due.</p>
</div>

<div class="section">
	<p><strong>What we do with it:</strong></p>

	<p>Your data will only be processed by our employees or authorised employees of the above
	mentioned third parties for the purposes of, providing our membership services to you and
	related business processes. No other third parties will have access to your data for this
	purpose unless required under law.</p>
</div>

<div class="section">
	<p><strong>Where do we store your data:</strong></p>

	<p>All your data is stored and processed securely within the EEA. We have data protection
	policies and procedures in place governing; who, how and when your data may be
	processed. We have implemented strong physical and digital security to protect any data
	located at our premises or directly on our servers and we have ensured all our partners have
	similar security in place as well. Access to your data is restricted and limited to those
	authorised including by legal contracts / agreements with the companies mentioned above to
	ensure they adhere to this.</p>
</div>

<div class="section">
	<p><strong>How long we keep your data:</strong></p>

	<p>We only keep your data for a reasonable time or for long as it is required based on the
	purpose it was originally collected, unless we are specifically required to keep it for longer by
	law. In any case, we will never keep your data in a personally identifiable manner for longer
	than 7 years. For full details please see our Data Retention Policy which can be found here.</p>
</div>

<div class="section">
	<p><strong>Other reasons we may use your data:</strong></p>

	<p>We may from time to time, like to use your name, email address and / or mobile number to
	inform you of any future offers and similar products / services that we feel may be of interest
	to you. We use two third parties who provide us technical services that enable us to contact
	you by email or text, they are: Text Marketer (Esendex Limited) and Mailchimp (The Rocket
	Science Group LLC). We will only process your data for marketing purposes using these third
	parties after we have received your explicit consent, you will be given the option to inform us
	of your preference at the end of the sign up process. You have the right to refuse consent and
	you can revoke your consent at any time using the unsubscribe link provided in all
	communications from us. Agreeing to this Privacy Statement alone does not give us consent
	to use your data for marketing.</p>

	<p>Mail Chimp is located in the US and as such we must inform you that part of your personal
	data may be processed outside of the EU if we market to you via email. We have a Data
	Protection Agreement in place with MailChimp and have reviewed their processes to ensure
	they operate to satisfactory data protection standards, they adhere to the US Privacy Shield
	standards which satisfies the requirements under the General Data Protection Regulations
	(GDPR) . Further details can be found in Section 10 of our Privacy Policy, a link to which can
	be found at the end of this statement.</p>
</div>

<div class="section">
	<p><strong>Your rights:</strong></p>

	<p>If at any point you believe that the information we process about you is incorrect you can
	request to see this information and have it corrected. You have the right to be forgotten and
	have your data erased, this right may be refused if we need to process your data to fulfil any
	contractual or legal requirements. If you have a complaint regarding our processing of your
	data you can contact us by email at compliance@visionhealthandfitness.co.uk
	If you are not satisfied with our response or believe we are processing your personal data
	unlawfully you can complain to the Information Commissioner’s Office (ICO) by visiting
	www.ico.org.uk</p>
</div>

<div class="section">
	<p><strong>Privacy Policies:</strong></p>

	<p>This privacy statement is designed to give you an understanding of who, why and how your
	your data will be processed, however for full in depth details we have provided you with links
	to our Privacy Policy and the Privacy Policies for all other third parties who may process the
	data you give to us. We advise that your read them.</p>
</div>

<ul>
	<li>Vision Health and Fitness Club Limited - <%= link_to 'Privacy Policy', privacy_policy_path %></li>
	<li>Membr (Fit Cloud Technology Limited) – <%= link_to 'Privacy Policy', 'https://membr.com/privacy-policy/' %></li>
	<li>Harlands Services Limited – <%= link_to 'Privacy policy', 'https://www.harlandsgroup.eu/wp-content/uploads/2018/06/Harlands-Privacy-Policy-2018.pdf' %></li>
	<li>Nomical Limited – <%= link_to 'Privacy Policy', 'https://nomical.com/privacy/' %></li>
	<li>Text Marketer – <%= link_to 'Privacy Policy', 'https://www.textmarketer.co.uk/pdfebooks/Text_Marketer_Security.pdf' %></li>
	<li>MailChimp – <%= link_to 'Privacy Policy', 'https://mailchimp.com/legal/privacy/?_ga=2.177046309.1262729590.1531221020-585560811.1526033649&_gac=1.220639850.1530875597.Cj0KCQjwpvzZBRCbARIsACe8vyKIMNkIKNj_UGx0Ytu8voeS6fIu2QAeYxP5JEBS6GPmSMCEW8HRq9kaAimnEALw_wcB' %></li>
</ul>