config/routes.rb
Rails.application.routes.draw do
  # Root
  root 'static_pages#home'

  # Backend
  namespace :backend do
    resources :users
    resources :trials
    resources :memberships
  end

  get '/swalwell/join', to: 'static_pages#swalwell_join', as: 'swalwell_join'
  get '/cramlington/join', to: 'static_pages#cramlington_join', as: 'cramlington_join'
  #get '/cramlington', to: 'static_pages#cramlington', as: 'cramlington'
  #get '/cramlington/gym-info', to: 'static_pages#cramlington_gym_info', as: 'cramlington_gym_info'
  #post '/cramlington/register-lead-interest', to: 'static_pages#cramlington_register_lead_interest', as: 'cramlington_register_lead_interest'
  #get '/cramlington/confirmation', to: 'static_pages#register_interest_confirmation', as: 'register_interest_confirmation'

	scope '/policies' do
  	get '/cookie_policy', to: 'static_pages#cookie_policy', as: 'cookie_policy'
  	get '/privacy_policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
	end

  get '/members', to: 'members#index'
  post '/members/import', to: 'members#import', as: 'import_members'

  get '/members/:consent_to_market_token', to: 'members#consent_to_market', as: :consent_to_market
  get '/members/consent_accepted/:consent_to_market_token', to: 'members#consent_accepted', as: :consent_accepted
  patch '/members/:consent_to_market_token', to: 'members#set_consent_to_market'

  # Front end
  #resources :trials,
  #  :memberships, only: [:new, :create, :index]
  #get '/memberships/thank-you', to: 'memberships#confirmation'
  #get '/trial-membership/thank-you', to: 'trials#confirmation'

  #get  '/signup',  to: 'users#new'
  #post '/signup',  to: 'users#create'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Classes
  get '/classes',                     to: 'static_pages#classes'
  #get '/classes/ab-solution',         to: 'static_pages#ab_solution'
  #get '/classes/bootcamp',            to: 'static_pages#bootcamp'
  #get '/classes/boxing',              to: 'static_pages#boxing'
  #get '/classes/circuit-training',    to: 'static_pages#circuit_training'
  #get '/classes/cycle-fit',           to: 'static_pages#cycle_fit'
  #get '/classes/cycle-pump',          to: 'static_pages#cycle_pump'
  #get '/classes/hiit',                to: 'static_pages#hiit'
  #get '/classes/kettle-x-fit',        to: 'static_pages#kettle_x_fit'
  #get '/classes/lbt',                 to: 'static_pages#lbt'
  #get '/classes/mma',                 to: 'static_pages#mma'
  #get '/classes/pilates',             to: 'static_pages#pilates'
  #get '/classes/pilates-hiit',        to: 'static_pages#pilates_hiit'
  #get '/classes/pumped',              to: 'static_pages#pumped'
  #get '/classes/rig-assault',         to: 'static_pages#rig_assault'
  #get '/classes/strength-and-conditioning',             to: 'static_pages#strength_and_conditioning'
  #get '/classes/total-body',          to: 'static_pages#total_body'
  #get '/classes/trx',                 to: 'static_pages#trx'
  #get '/classes/ultimate-endurance',  to: 'static_pages#ultimate_endurance'

  get '/facilities',                  to: 'static_pages#facilities'
  #get '/timetables',                  to: 'static_pages#timetables'

  get '/vhf_code_of_conduct',         to: 'static_pages#vhf_code_of_conduct'

  # Contact
  get '/contact',                     to: 'messages#new', as: 'new_message'
  post '/contact',                    to: 'messages#create', as: 'create_message'

  # Letter opener path for development only
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/trial.rb
class Trial < ApplicationRecord
  before_save { email.downcase! }

  validates :first_name, :last_name, :contact_number, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :contact_number, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  STATUSES = ['PENDING', 'ACCEPTED', 'DECLINED']
end

app/controllers/backend/base_controller.rb
module Backend
 class BaseController < ActionController::Base
   layout "layouts/application"
   protect_from_forgery with: :exception
   include SessionsHelper

   before_action :logged_in_user
 end
end

app/controllers/backend/memberships_controller.rb
module Backend
  class MembershipsController < BaseController
    # GET /backend/memberships
    def index
      @memberships = Membership.all
    end

    # GET /backend/memberships/new
    def new
      @membership_options = MembershipOption.all
      @membership = Membership.new
    end

    # GET /backend/memberships/:id
    def show
      @membership = Membership.find(params[:id])
    end

    def destroy
      Membership.find(params[:id]).destroy
      flash[:success] = "Membership deleted"
      redirect_to backend_memberships_url
    end
  end
end

app/controllers/backend/trials_controller.rb
module Backend
  class TrialsController < BaseController
    #GET /backend/trials
    def index
      @trials = Trial.all
    end

    #GET /backend/trials/:id
    def show
      @trial = Trial.find(params[:id])
    end

    #GET /backend/trials/new
    def new
      @trial = Trial.new
    end

    #POST /backend/trials
    def create
      @trial = Trial.new(trial_params)
      set_trial_status 
      if @trial.save
        TrialMailer.trial_message(@trial).deliver_now
        redirect_to trial_membership_thank_you_url
      end
    end

    #GET /backend/trials/:id/edit
    def edit
      @trial = Trial.find(params[:id])
    end

    #POST /backend/trials/:id
    def update
      @trial = Trial.find(params[:id])
      if @trial.update_attributes(trial_params)
        flash[:success] = "Trial updated"
        redirect_to @trial
      else
        render 'edit'
      end
    end

    #POST /backend/trials/:id
    def destroy
      Trial.find(params[:id]).destroy
      flash[:success] = "Trial deleted"
      redirect_to trials_url
    end

    def confirmation
    end

    private

      def trial_params
        params.require(:trial).permit(:first_name, :last_name, :email, :contact_number, :status)
      end

      def set_trial_status
        @trial.status = 'PENDING' if @trial.status.nil?
      end
  end
end

app/controllers/backend/users_controller.rb
module Backend
  class UsersController < BaseController
    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "User created"
        redirect_to @user
      else
        render 'new'
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'edit'
      end
    end

    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    end

    private

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

      # Confirms the correct user.
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end
  end
end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  def new
    @trial = Trial.new
  end

  def create
    @trial = Trial.new(trial_params)
    set_trial_status 
    if @trial.save
      TrialMailer.trial_message(@trial).deliver_now
      redirect_to trial_membership_thank_you_path
    elsif @trial.errors.any?
      flash.now[:error] = @trial.errors.full_messages
      render :new
    end
  end

  def confirmation
  end

  private

    def trial_params
      params.require(:trial).permit(:first_name, :last_name, :email, :contact_number, :status)
    end

    def set_trial_status
      @trial.status = 'PENDING'
    end

end

app/views/backend/trials/_form.haml
= form_for(@trial) do |f|
  = f.label :first_name
  = f.text_field :first_name
  = f.label :last_name
  = f.text_field :last_name
  = f.label :email
  = f.email_field :email
  = f.label :contact_number
  = f.text_field :contact_number
  = f.label :status
  = f.select :status, Trial::STATUSES
  = f.button yield(:button_text), class: "small-12 button"

app/views/backend/trials/confirmation.haml
%p Thank you

app/views/backend/trials/edit.haml
- provide(:title, 'Edit New Trial')
- provide(:button_text, 'Save')
.row
  .small-12.medium-6.small-centered.columns
    %h1 Edit trial
.row
  .small-12.medium-6.small-centered.columns
    = render 'form'

app/views/backend/trials/index.haml
- provide(:title, 'All trial memberships')
.row
  .small-12.columns
    %h1 Trial Memberships
.row
  .small-12.columns
    = link_to 'New Trial', new_trial_path, class: 'button green'
.row
  .small-12.columns
    .table-scroll
      %table
        %thead
          %tr
            %th First Name
            %th Last Name
            %th Email
            %th Contact Number
            %th Status
            %th Actions
        %tbody
          - @trials.each do |trial|
            %tr
              %td= trial.first_name
              %td= trial.last_name
              %td= trial.email
              %td= trial.contact_number
              %td= trial.status
              %td
                .button.blue= link_to 'View', backend_trial_path(trial)
                .button.amber= link_to 'Edit', edit_backend_trial_path(trial)
                .button= link_to 'Delete', backend_trial_path(trial), :method => :delete, :confirm => "Are you sure ?"

app/views/backend/trials/new.haml
- provide(:title, 'Create New Trial')
- provide(:button_text, 'Create Trial')
.row
  .small-12.medium-6.small-centered.columns
    %h1 Create new trial
.row
  .small-12.medium-6.small-centered.columns
    = render 'form'

app/views/backend/trials/show.haml
.row.vertical-spacing
  .small-12.medium-8.medium-centered.columns
    %p
      %b Name: 
      = "#{@trial.first_name} #{@trial.last_name}"
    %p
      %b Email: 
      = @trial.email
    %p
      %b Contact Number: 
      = @trial.contact_number
    %p
      %b Status:
      = @trial.status